CREATE_USER_TABLE_QUERY = '''CREATE TABLE IF NOT EXISTS telegramm_users(
id INTEGER PRIMARY KEY,
first_name TEXT,
tg_id INTEGER,
UNIQUE(tg_id))'''
INSERT_USER_QUERY = '''INSERT OR IGNORE INTO telegramm_users VALUES (?, ?, ?)'''

SELECT_USER = '''SELECT * FROM telegramm_users'''


CREATE_PROFILE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS profiles 
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
BIO CHAR(50),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_PROFILE_QUERY = """
INSERT INTO profiles VALUES(?,?,?,?,?)
"""